FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

RUN mkdir /datadm
WORKDIR /datadm

COPY README.md /datadm
COPY pyproject.toml /datadm
COPY datadm/ /datadm/datadm

RUN SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0 pip install -e ".[cuda]"

CMD ["datadm"]